### ISSUE TITLE
Cant connect to SQL Server DataBase When compiling with Docker 

### ISSUE THREAD

**Issue by PapisKang** [app-generator/docs#59]
Hi EveryOne 
First of all this issue came only when compiling with Docker. 
With the manual build, i dont have any issue.
 
I m trying to connect the App to my SQL Server Database 
My dataBase is fully accessible and the connexion is tested with a little program.
But I cant do the same with the Flask Soft Dashboard 
I edited my SQL ALCHEMY URI with 
` SQLALCHEMY_DATABASE_URI = f"mssql+pyodbc://{DB_USERNAME}:{DB_PASS}@{DB_HOST}/{DB_NAME}?driver=ODBC+Driver+17+for+SQL+Server"`

I added to the requirement text, the package pyodbc

The URI is tested and works. 

I ve this error 
` => ERROR [appseed-app 7/9] RUN flask db init                                                                                                                                      1.5s
------
 > [appseed-app 7/9] RUN flask db init:
1.387 Error: While importing 'run', an ImportError was raised:
1.387
1.387 Traceback (most recent call last):
1.387   File "/usr/local/lib/python3.10/site-packages/flask/cli.py", line 218, in locate_app
1.387     __import__(module_name)
1.387   File "/run.py", line 31, in <module>
1.387     app = create_app(app_config)
1.387   File "/apps/__init__.py", line 56, in create_app
1.387     register_extensions(app)
1.387   File "/apps/__init__.py", line 19, in register_extensions
1.387     db.init_app(app)
1.387   File "/usr/local/lib/python3.10/site-packages/flask_sqlalchemy/extension.py", line 329, in init_app
1.387     engines[key] = self._make_engine(key, options, app)
1.387   File "/usr/local/lib/python3.10/site-packages/flask_sqlalchemy/extension.py", line 617, in _make_engine
1.387     return sa.engine_from_config(options, prefix="")
1.387   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 755, in engine_from_config
1.387     return create_engine(url, **options)
1.387   File "<string>", line 2, in create_engine
1.387   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/util/deprecations.py", line 309, in warned
1.387     return fn(*args, **kwargs)
1.387   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 560, in create_engine
1.387     dbapi = dialect_cls.dbapi(**dbapi_args)
1.387   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/connectors/pyodbc.py", line 43, in dbapi
1.387     return __import__("pyodbc")
1.387 ImportError: libodbc.so.2: cannot open shared object file: No such file or directory
1.387
1.387
1.387 Usage: flask [OPTIONS] COMMAND [ARGS]...
1.387 Try 'flask --help' for help.
1.387
1.388 Error: No such command 'db'.
------
failed to solve: process "/bin/sh -c flask db init" did not complete successfully: exit code: 2`

**Comment by app-generator** [comment]
https://github.com/mkleehammer/pyodbc/wiki/Install#installing-on-linux

Hello @PapisKang 

A solution might be to install `unixodbc` package. Here is the EXEC for Ubuntu:

```bash
$ sudo apt install unixodbc
```

Let us know if the patch worked.
